services:
  auth-server:
    container_name: auth-server
    image: domboeckli/spring-6-auth-server:0.0.5-SNAPSHOT
    ports:
      - "9000:9000"
    expose:
      - 9000
    environment:
      SPRING_SECURITY_OAUTH2_AUTHORIZATION_SERVER_ISSUER: http://localhost:9000
