nameOverride: "spring-6-rest-mvc"
fullnameOverride: "spring-6-rest-mvc"

global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: spring-6-rest-mvc

replicaCount: 1

image:
  # Those values are set by Maven filtering
  # and will be replaced with a valid version number during the build process.
  registry: @docker.repo@
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081
  targetPort: 8081
  nodePort: 30081

externalAccess:
  host: "localhost"
  protocol: "http"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

spring:
  profiles:
    active: mysql
  oauth2ResourceServer:
    issuerUri: ""

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

mysql:
  enabled: true

  fullnameOverride: "spring-6-rest-mvc-mysql"

  database: restmvcdb

  port: 3306
  targetPort: 3306
  nodePort: 30306

  user: restadmin
  password: password

  rootPassword: verysecret

  serviceFQDN: "spring-6-rest-mvc-mysql.spring-6-rest-mvc.svc.cluster.local"

kafka:
  enabled: true

  fullnameOverride: "spring-6-rest-mvc-kafka"

  port: 9092
  serviceFQDN: "spring-6-rest-mvc-kafka.spring-6-rest-mvc.svc.cluster.local"

authServer:
  enabled: true

  port: 9000
  targetPort: 9000
  nodePort: 30900

  serviceFQDN: "spring-6-auth-server.spring-6-rest-mvc.svc.cluster.local"

coldMicroService:
  enabled: true
  port: 8081
  serviceFQDN: "spring-6-cold-micro-service.spring-6-rest-mvc.svc.cluster.local"

coolMicroService:
  enabled: true
  port: 8082
  serviceFQDN: "spring-6-cool-micro-service.spring-6-rest-mvc.svc.cluster.local"

icecoldMicroService:
  enabled: true
  port: 8080
  serviceFQDN: "spring-6-icecold-micro-service.spring-6-rest-mvc.svc.cluster.local"

ingress:
  enabled: false

# Section for overriding values in subcharts.
spring-6-auth-server-chart:
  spring:
    issuer:
      uri: "http://spring-6-auth-server.spring-6-rest-mvc.svc.cluster.local:9000"

spring-6-cold-micro-service-chart:
  fullnameOverride: spring-6-cold-micro-service
  service:
    # default 30081 collides with the rest-mvc NodePort
    nodePort: 30091
  kafka:
    enabled: false
    serviceFQDN: "spring-6-rest-mvc-kafka.spring-6-rest-mvc.svc.cluster.local"
    port: 9092
    clientPort: 9092

spring-6-cool-micro-service-chart:
  fullnameOverride: spring-6-cool-micro-service
  service:
    nodePort: 30082
  kafka:
    enabled: false
    serviceFQDN: "spring-6-rest-mvc-kafka.spring-6-rest-mvc.svc.cluster.local"
    port: 9092
    clientPort: 9092

spring-6-icecold-micro-service-chart:
  fullnameOverride: spring-6-icecold-micro-service
  service:
    nodePort: 30080
  kafka:
    enabled: false
    serviceFQDN: "spring-6-rest-mvc-kafka.spring-6-rest-mvc.svc.cluster.local"
    port: 9092
    clientPort: 9092


