apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-6-rest-mvc-mysql.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "spring-6-rest-mvc-mysql.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | quote }}

  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_ADMIN_USER: {{ .Values.mysql.adminUser | quote }}
  MYSQL_ADMIN_PASSWORD: {{ .Values.mysql.adminPassword | quote }}
